### ISSUE TITLE
Updating failing

### ISSUE THREAD

**Issue by martinjh99** [diakweb/docker-tinytinyrss#2]
When using your container everything work fine apart from updaing feeds - I get this error for every feed I have subscribed to...

```
E_USER_NOTICE (1024) | :0 | Update process for feed 46 (Mozilla Security Blog, owner UID: 2) failed with exit code: 127 ().
```

Not sure what's happening there... Unless it is a problem with ttrss itself other than your container...

**Comment by diakweb** [comment]
It was a problem with my container, sorry.
I fixed it i think. Update it and tell me if it's ok.

**Comment by martinjh99** [comment]
Looks ok to me now with a build of the new container.

Thanks :)

**Comment by diakweb** [comment]
Great !
I close the issue :)
